

GWSOrder = ['ATGOrderNumber', 'o356451'
            'CustomerID',''
            'SalesChannel',''
            'Origin',''
            'Webstore',''
            'Language',''
            'SaleCurrency',''
            'TransferCurrency',''
            'DistributionCentre',''
            'OrderTotal',''
            'DateEntered',''
            'Source',''
            'IsStaffOrder',''
            'IsGift',''
            'Type', ''
            'shipToStoreID',''
            'FirstName',''
            'LastName',''
            'Address1',''
            'Address2',''
            'City',''
            'StateProvince',''
            'PostalCode',''
            'Country',''
            'ContactPhone',''
            'ContactEmail',''
            'GWSOrderNumber',''
            'ShippingTotal',''
            'IsShippingTotalTaxInclusive',''
            'Type',''
            'Rate',''
            'Amount',''
            'ProductCode',''
            'Description',''
            'LineNumber',''
            'QuantityOrdered',''
            'RetailPrice',''
            'SalesPrice',''
            'TransferPrice',''
            'IsTaxInclusive',''
            'IsBundleHeader',''
            'Rate',''
            'Amount',''
            'Type',''
            'Amount',''
            'Reference',''
            'PaidInStoreID','']

