import xml.etree.ElementTree as ET

input = '''

<Message>
    <Lpn>
      <FacilityAliasID>ED</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905034069</TCLpnID>
      <EstimatedWeight>78.2</EstimatedWeight>
      <Weight>78.2</Weight>
      <Volume>233043.36</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-12</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>01010599001</Item>
        <ActualQuantity>23</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>ED</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905034083</TCLpnID>
      <EstimatedWeight>102</EstimatedWeight>
      <Weight>102</Weight>
      <Volume>303969.6</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-12</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>60010599001</Item>
        <ActualQuantity>30</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>ED</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905034106</TCLpnID>
      <EstimatedWeight>221.678</EstimatedWeight>
      <Weight>221.678</Weight>
      <Volume>273630.816</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-12</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>04040599012</Item>
        <ActualQuantity>818</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>ED</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905034113</TCLpnID>
      <EstimatedWeight>150.947</EstimatedWeight>
      <Weight>150.947</Weight>
      <Volume>186323.184</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-12</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>60040599012</Item>
        <ActualQuantity>557</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>EM</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905062024</TCLpnID>
      <EstimatedWeight>42.84</EstimatedWeight>
      <Weight>42.84</Weight>
      <Volume>105019.2</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-13</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>60100181457</Item>
        <ActualQuantity>120</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>EM</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905062031</TCLpnID>
      <EstimatedWeight>17.96</EstimatedWeight>
      <Weight>17.96</Weight>
      <Volume>37422</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-13</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>04100181123</Item>
        <ActualQuantity>40</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>EM</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905062048</TCLpnID>
      <EstimatedWeight>18.52</EstimatedWeight>
      <Weight>18.52</Weight>
      <Volume>38388.24</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-13</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>04100281020</Item>
        <ActualQuantity>40</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>EM</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905062055</TCLpnID>
      <EstimatedWeight>39.12</EstimatedWeight>
      <Weight>39.12</Weight>
      <Volume>93600</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-13</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>60100181454</Item>
        <ActualQuantity>60</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>EM</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905062062</TCLpnID>
      <EstimatedWeight>26.08</EstimatedWeight>
      <Weight>26.08</Weight>
      <Volume>62400</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-13</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>60100181454</Item>
        <ActualQuantity>40</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>EM</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905062079</TCLpnID>
      <EstimatedWeight>85.68</EstimatedWeight>
      <Weight>85.68</Weight>
      <Volume>210038.4</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-13</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>60100181457</Item>
        <ActualQuantity>240</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>EM</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905062086</TCLpnID>
      <EstimatedWeight>14.28</EstimatedWeight>
      <Weight>14.28</Weight>
      <Volume>35006.4</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
     <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-13</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>60100181457</Item>
        <ActualQuantity>40</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>EM</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905062093</TCLpnID>
      <EstimatedWeight>28.38</EstimatedWeight>
      <Weight>28.38</Weight>
      <Volume>58687.2</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-13</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>01100181278</Item>
        <ActualQuantity>60</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>EM</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905062109</TCLpnID>
      <EstimatedWeight>9.46</EstimatedWeight>
      <Weight>9.46</Weight>
      <Volume>19562.4</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-13</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>01100181278</Item>
        <ActualQuantity>20</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>EM</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905062116</TCLpnID>
      <EstimatedWeight>25.44</EstimatedWeight>
      <Weight>25.44</Weight>
      <Volume>50965.2</Volume>
     <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-13</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>01100281029</Item>
        <ActualQuantity>60</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>EM</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905062123</TCLpnID>
      <EstimatedWeight>8.48</EstimatedWeight>
      <Weight>8.48</Weight>
      <Volume>16988.4</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-13</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>01100281029</Item>
        <ActualQuantity>20</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>ED</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905062130</TCLpnID>
      <EstimatedWeight>13.021</EstimatedWeight>
      <Weight>13.021</Weight>
      <Volume>27130.95</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-13</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>04100181123</Item>
        <ActualQuantity>29</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>ED</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905062147</TCLpnID>
      <EstimatedWeight>13.427</EstimatedWeight>
      <Weight>13.427</Weight>
      <Volume>27831.474</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-13</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>04100281020</Item>
        <ActualQuantity>29</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>ED</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905062154</TCLpnID>
      <EstimatedWeight>18.908</EstimatedWeight>
      <Weight>18.908</Weight>
      <Volume>45240</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-13</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>60100181454</Item>
        <ActualQuantity>29</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>ED</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905062178</TCLpnID>
      <EstimatedWeight>16.082</EstimatedWeight>
      <Weight>16.082</Weight>
      <Volume>33256.08</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-13</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>01100181278</Item>
        <ActualQuantity>34</ActualQuantity>
      </LpnDetail>
    </Lpn>
    <Lpn>
      <FacilityAliasID>ED</FacilityAliasID>
      <TCCompanyID>55</TCCompanyID>
      <TCLpnID>00000999991905062185</TCLpnID>
      <EstimatedWeight>14.416</EstimatedWeight>
      <Weight>14.416</Weight>
      <Volume>28880.28</Volume>
      <Location>00/AC/1/010</Location>
      <Area>R</Area>
      <Aisle>00</Aisle>
      <Bay>AC</Bay>
      <Level>1</Level>
      <Position>01</Position>
      <InboundOutboundIndicator>I</InboundOutboundIndicator>
      <LpnFacilityStatus>30</LpnFacilityStatus>
      <ReceivedDate>0017-11-13</ReceivedDate>
      <LpnDetail>
        <LPNDetailID>1</LPNDetailID>
        <TCCompanyID>55</TCCompanyID>
        <Item>01100281029</Item>
        <ActualQuantity>34</ActualQuantity>
      </LpnDetail>
    </Lpn>
  </Message>  
'''
input = open(rough_data.xml r)


Message = ET.fromstring(input)
lst = Message.findall('Lpn/LpnDetail')
print('LPN count:', len(lst))

for item in lst:
    print('Item', item.find('Item').text)
    print( 'ActualQuantity', item.find('ActualQuantity').text)
