from xml.dom import minidom


root = minidom.Document()


SalesOrder = root.createElement('SalesOrder')
root.appendChild(SalesOrder)

ATGOrderNumber = root.createElement('ATGOrderNumber')
SalesOrder.appendChild(ATGOrderNumber)
ATGOrderNumber.appendChild(root.createTextNode('o65897'))


CustomerID = root.createElement('CustomerID')
SalesOrder.appendChild(CustomerID)
SalesChannel = root.createElement('SalesChannel')
SalesOrder.appendChild(SalesChannel)


Origin = root.createElement('Origin')
SalesOrder.appendChild(Origin)
Webstore = root.createElement('Webstore')
SalesOrder.appendChild(Webstore)
Language = root.createElement('Language')
SalesOrder.appendChild(Language)
TransferCurrency = root.createElement('TransferCurrency')
SalesOrder.appendChild(TransferCurrency)
DistributionCentre = root.createElement('DistributionCentre')
SalesOrder.appendChild(DistributionCentre)
OrderTotal = root.createElement('OrderTotal')
SalesOrder.appendChild(OrderTotal)
DateEntered = root.createElement('DateEntered')
SalesOrder.appendChild(DateEntered)
Source = root.createElement('Source')
SalesOrder.appendChild(Source)
IsStaffOrder = root.createElement('IsStaffOrder')
SalesOrder.appendChild(IsStaffOrder)
IsGift = root.createElement('IsGift')
SalesOrder.appendChild(IsGift)

Addresses = root.createElement('Addresses')
SalesOrder.appendChild(Addresses)


Address = root.createElement('Address')
Addresses.appendChild(Address)


ATGOrderNumber = root.createElement('ATGOrderNumber')
Address.appendChild(ATGOrderNumber)



Type = root.createElement('Type')
Address.appendChild(Type)
ShipToStoreID = root.createElement('ShipToStoreID')
Address.appendChild(ShipToStoreID)
FirstName = root.createElement('FirstName')
Address.appendChild(FirstName)
LastName = root.createElement('LastName')
Address.appendChild(LastName)
Address1 = root.createElement('Address1')
Address.appendChild(Address1)
Address2 = root.createElement('Address2')
Address.appendChild(Address2)
City = root.createElement('City')
Address.appendChild(City)
StateProvince = root.createElement('StateProvince')
Address.appendChild(StateProvince)
PostalCode = root.createElement('PostalCode')
Address.appendChild(PostalCode)
Country = root.createElement('Country')
Address.appendChild(Country)
ContactPhone = root.createElement('ContactPhone')
Address.appendChild(ContactPhone)
ContactEmail = root.createElement('ContactEmail')
Address.appendChild(ContactEmail)
ShippingGroups = root.createElement('ShippingGroups')
SalesOrder.appendChild(ShippingGroups)
ShippingGroup = root.createElement('ShippingGroup')
ShippingGroups.appendChild(ShippingGroup)
GWSOrderNumber = root.createElement('GWSOrderNumber')
ShippingGroup.appendChild(GWSOrderNumber)
ATGOrderNumber = root.createElement('ATGOrderNumber')
ShippingGroup.appendChild(ATGOrderNumber)
ShippingTotal = root.createElement('ShippingTotal')
ShippingGroup.appendChild(ShippingTotal)
IsShippingTotalTaxInclusive = root.createElement('IsShippingTotalTaxInclusive')
ShippingGroup.appendChild(IsShippingTotalTaxInclusive)
ShippingTaxes = root.createElement('ShippingTaxes')
ShippingGroup.appendChild(ShippingTaxes)
ShippingTax = root.createElement('ShippingTax')
ShippingTaxes.appendChild(ShippingTax)

GWSOrderNumber = root.createElement('GWSOrderNumber')
ShippingTax.appendChild(GWSOrderNumber)

Type = root.createElement('Type')
ShippingTax.appendChild(Type)
Rate = root.createElement('Rate')
ShippingTax.appendChild(Rate)
Amount = root.createElement('Amount')
ShippingTax.appendChild(Amount)

ShippingMethod = root.createElement('ShippingMethod')
ShippingGroup.appendChild(ShippingMethod)
OrderType = root.createElement('OrderType')
ShippingGroup.appendChild(OrderType)

OrderDetails = root.createElement('OrderDetails')
ShippingGroup.appendChild(OrderDetails)
OrderDetail = root.createElement('OrderDetail')
OrderDetails.appendChild(OrderDetail)
GWSOrderNumber = root.createElement('GWSOrderNumber')
OrderDetail.appendChild(GWSOrderNumber)
ProductCode = root.createElement('ProductCode')
OrderDetail.appendChild(ProductCode)
Description = root.createElement('Description')
OrderDetail.appendChild(Description)
LineNumber = root.createElement('LineNumber')
OrderDetail.appendChild(LineNumber)
QuantityOrdered = root.createElement('QuantityOrdered')
OrderDetail.appendChild(QuantityOrdered)
RetailPrice = root.createElement('RetailPrice')
OrderDetail.appendChild(RetailPrice)
SalesPrice = root.createElement('SalesPrice')
OrderDetail.appendChild(SalesPrice)
TransferPrice = root.createElement('TransferPrice')
OrderDetail.appendChild(TransferPrice)
IsTaxInclusive = root.createElement('IsTaxInclusive')
OrderDetail.appendChild(IsTaxInclusive)
IsBundleHeader = root.createElement('IsBundleHeader')
OrderDetail.appendChild(IsBundleHeader)

Taxes = root.createElement('Taxes')
OrderDetail.appendChild(Taxes)
Tax = root.createElement('Tax')
Taxes.appendChild(Tax)
GWSOrderNumber = root.createElement('GWSOrderNumber')
Tax.appendChild(GWSOrderNumber)
LineNumber = root.createElement('LineNumber')
Tax.appendChild(LineNumber)
Type = root.createElement('Type')
Tax.appendChild(Type)
Rate = root.createElement('Rate')
Tax.appendChild(Rate)
Amount = root.createElement('Amount')
Tax.appendChild(Amount)

Payments = root.createElement('Payments')
SalesOrder.appendChild(Payments)
Payment = root.createElement('Payment')
Payments.appendChild(Payment)
ATGOrderNumber = root.createElement('ATGOrderNumber')
Payment.appendChild(ATGOrderNumber)
Type = root.createElement('Type')
Payment.appendChild(Type)
Amount = root.createElement('Amount')
Payment.appendChild(Amount)
Reference = root.createElement('Reference')
Payment.appendChild(Reference)
PaidInStoreID = root.createElement('PaidInStoreID')
Payment.appendChild(PaidInStoreID)





xml_str =root.toprettyxml(indent="\t")
save_path_file = "weborder.xml"

with open(save_path_file, "w")as f:
    f.write(xml_str)